#!/usr/bin/env php
<?php

use App\Main\Application;

require __DIR__ . '/vendor/autoload.php';

if(!isset($_SERVER['DOCUMENT_ROOT']) || empty($_SERVER['DOCUMENT_ROOT'])) {
    $_SERVER['DOCUMENT_ROOT'] = __DIR__;
}

$args = array_slice($_SERVER['argv'], 1);
$application = new Application($args);
$application->run();
